[project]
authors = ["Pinak Paliwal (pinak@locamage.dev)"]
channels = ["conda-forge"]
description = "Jax Image Models"
name = "jim"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11.13,<3.12"
ipykernel = ">=6.29.5,<7"
pillow = ">=11.2.1,<12"

[pypi-dependencies]
flax = ">=0.10.6, <0.11"
ml-collections = ">=1.1.0, <2"
jaxtyping = ">=0.3.2, <0.4"
safetensors = ">=0.5.3, <0.6"
transformers = ">=4.52.4, <5"
torch = ">=2.7.1, <3"

[feature.cuda]
platforms = ["linux-64"]
channels = [{ channel = "nvidia", priority = 1 }, "conda-forge"]

[feature.cuda.dependencies]

[feature.cuda.pypi-dependencies]
jax = { version = ">=0.5.2, <0.6", extras = ["cuda12"] }

[feature.cuda.pypi-options]
no-build-isolation = []

[feature.cuda.system-requirements]
cuda = "12"

[feature.tpu]
platforms = ["linux-64"]
channels = ["pytorch", "conda-forge"]

[feature.tpu.dependencies]

[feature.tpu.pypi-dependencies]
jax = { version = ">=0.5.2, <0.6", extras = ["tpu"] }
tpu-info = ">=0.3.0, <0.4"

[feature.dev.dependencies]
pytest = ">=8.4.0,<9"
pre-commit = ">=4.2.0,<5"
ruff = ">=0.11.13,<0.12"
pip = ">=25.1.1,<26"
mkdocstrings-python = ">=1.16.12,<2"


[feature.dev.pypi-dependencies]
tensorflow-datasets = ">=4.9.9, <5"
tensorflow = ">=2.19.0, <3"
mkdocs-material = ">=9.6.14, <10"


[environments]
default = { features = ["cuda", "dev"], solve-group = "main" }
cuda = { features = ["cuda"], solve-group = "main" }
tpu = { features = ["tpu"], solve-group = "main" }
cuda-dev = { features = ["cuda", "dev"], solve-group = "main" }
tpu-dev = { features = ["tpu", "dev"], solve-group = "main" }
