name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: curl -fsSL https://pixi.sh/install.sh | sh
      - run: /root/.pixi/bin/pixi run -e cuda-dev pip install -e .
      - run: /root/.pixi/bin/pixi run -e cuda-dev pip install mkdocs-material mkdocstrings[python]
      - run: /root/.pixi/bin/pixi run -e cuda-dev mkdocs gh-deploy --force